package com.zfinance.authmanager.enums;

public enum ZFinConfigsEnum {
	TEMP_NO_LDAP_PASS_KEY("TEMP_NO_LDAP_PASS_KEY"), LDAP_ADMIN_USER("LDAP_ADMIN_USER"), LDAP_ADMIN_PASSWORD(
			"LDAP_ADMIN_PASSWORD"), LDAP_BASE("LDAP_BASE"), LDAP_IDENTITY_ATTRIBUTE("LDAP_IDENTITY_ATTRIBUTE"),
	LDAP_DOMAIN("LDAP_DOMAIN"), LDAP_IPS("LDAP_IPS"), LDAP_CONNECTION_TYPE("LDAP_CONNECTION_TYPE"), LDAP_PORT(
			"LDAP_PORT"), VERIFICATION_EMAIL_SUBJECT("VERIFICATION_EMAIL_SUBJECT"), VERIFICATION_EMAIL_BODY(
					"VERIFICATION_EMAIL_BODY"), OTP_SUBJECT("OTP_SUBJECT"), OTP_BODY("OTP_BODY"),
	DEFAULT_SIGN_IN_SUBJECT("DEFAULT_SIGN_IN_SUBJECT"), DEFAULT_PASSWORD_BODY("DEFAULT_PASSWORD_BODY"), PARTNER_ID_BODY(
			"PARTNER_ID_BODY"), QR_CODE_AUTH_SUBJECT("QR_CODE_AUTH_SUBJECT"), QR_CODE_AUTH_BODY("QR_CODE_AUTH_BODY");

	private String code;

	private ZFinConfigsEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
